### ISSUE TITLE
Indicator when talking

### ISSUE THREAD

**Issue by ghost** [Camorte/IVR-Connection#4]
# Improving communication
## Problems

- Hard to "jump in" on a conversation when using voice over the net
- It is not possible to see who is speaking through VR

## Strategy
Listen in on the client-side microphone, and have some sort of indicator light up when someone talks.

If #3 is implemented, maybe have some sort of object that you have to hold in your hands to be able to speak?

**Comment by mar2n** [comment]
Indicator added, but is currently only triggered by button input

**Comment by asbjoree** [comment]
## 8th milestone update
A manual indicator has been added. This works by letting the user press a button in order to display an indicator by their name. The user must manually hold the button when speaking in order to get the proper effect.

The next step would be to implement an automatic voice indicator. This indicator will listen to the microphone levels and determine when a player is speaking, then display the indicator automatically.

**Comment by asbjoree** [comment]
Should now be working as of commit f6d2fab in the VoiceIndicator branch. Awaiting review.
